### ISSUE TITLE
Move model to external harddrive and symlink it

### ISSUE THREAD

**Issue by rowild** [ex3ndr/llama-coder#18]
This is actually a question not an issue:

Where does the VS Code extension download the model to? 
Is there a way to choose the location where the model can be saved to?

I am testing lots of UIs for LLMs and therefore come into the situation that a model is downloaded rather often. This reduces disk space very quickly. For things likes Stable Diffusion with Automatic1111, ComfyUI, Fooocus, StabelSwarm etc it is easy to either set a custom source folder via the software's settings or to manually create a symlinked folder. Then I only need the models once.

Here it is no really clear where the model is saved to, which is something that tends to create distrust. I would very much like to be able to see where things are downloaded to, and even better: I would like to set options for things like that.

Would that be possible to implement here, too?

Also – since this is not an issue: Can I motivate you to open the "Discussions" panel here in your github repo? That would provide a "Questions" section, where this topic would fit better. Thank you! :-)

**Comment by ex3ndr** [comment]
That's fine to ask questions here.

I don't know how to configure target folder for ollama, but i am sure you would find something in their repo.

**Comment by rowild** [comment]
@ex3ndr Thank you for your feedback! I indeed found the local folder '.ollama', which was the location where the model was saved to. I could symlink the specific folder to my external drive and so far everything seems to work fine.
