### ISSUE TITLE
Add setting to reduce autocomplete suggestions

### ISSUE THREAD

**Issue by quikssb** [ex3ndr/llama-coder#19]
I noticed that on every little change in the file, the extension will give me autocompletion suggestion. Often they are not necessary and "random" since they lack context.

Additionally this causes a big overheat and makes Ollama crash easily on my PC. So I suggest a feature would be nice, which regulates the amount of requests the extension does to the model. Something like an additional setting would be nice, which can be regulated by the user (e.g. make request of autocomplete to the model only 0.5 seconds after the user didn't input anything in the editor).

**Comment by JojoJr24** [comment]
Hi developers,
First of all, I love this project, works really well with codellama!!

Second, I'm agree with quikssb. I think that the bounce time could be an option or could be key shortcut to trigger the autocomplete.
Thank you very much for this project!!
