### ISSUE TITLE
Please add Deepseek-coder models

### ISSUE THREAD

**Issue by ragaman555** [ex3ndr/llama-coder#2]
Hi,

can you please update the extension to enable usage the new Deepseek-coder models.
The models are already implemented in Ollama and outperforms code-lama models.

[deepseek-coder](https://ollama.ai/library/deepseek-coder)

Thank you.

**Comment by ex3ndr** [comment]
As i can see it has only instruct models: https://ollama.ai/library/deepseek-coder/tags, but we need a base one. I will check if instruct versions are useful.

**Comment by ex3ndr** [comment]
I have tried to use instruct model and it is far from satifactory one.
<img width="1940" alt="image" src="https://github.com/ex3ndr/llama-coder/assets/400659/fd673a96-c573-4f10-acdb-0112938781b4">

**Comment by paramaggarwal** [comment]
The base models are available now `ollama run deepseek-coder:6.7b`

**Comment by ex3ndr** [comment]
@jmorganca said that he would upload base models: https://x.com/jmorgan/status/1728179991567880610?s=20

**Comment by ex3ndr** [comment]
Deepseek models are added in v0.0.8

**Comment by ex3ndr** [comment]
Actually, there is still a problem for long files.

**Comment by ex3ndr** [comment]
Deepseek models are added, but be sure to have latest ollama.

**Comment by leoauri** [comment]
In the readme there are notations for which codellama models run slowly on M1. Can someone advise on deepseek models?
