### ISSUE TITLE
Avoid downloading models if already installed using ollama

### ISSUE THREAD

**Issue by erf** [ex3ndr/llama-coder#8]
I already installed the `codellama` and `deepseek-llm` models using `ollama` but your vscode extensions `llama-coder` is now displaying `downloading..`, so i guess it's downloading additional models needed. Would it be possible you could check if the models already exists on the system and make downloading them optional to save time and space?

**Comment by ex3ndr** [comment]
I limit number of models that plugin supports, but i will add deepseek-llm one

**Comment by erf** [comment]
> I suspect that your problem arises because you downloaded the default model tag (see https://ollama.ai/library/codellama/tags) and llama-coder uses the desired quantization tag, which is why ollama downloads a new model.

Makes sense, but i wonder why "limit number of models that plugin supports", as it can't be that much difference in the various tags under `codellama`, like the latest tag that is the default download. Loading an additional 4-10 GB is not a small download. Why not leave this up to the end user to decide what type of model to use, or is the model data that difference that it wouldn't work?

**Comment by tikendraw** [comment]
Also, It should ask if you want to download or not, any notification or pop up would be nice.
I have 6 different models [including codellama, deepseek coder6.7b]  installed using ollama but this thing thought downloading another model would be fun.
I use metered connection and this  fucking thing just started downloading without any notification , it exhausted my daily limit for two days,

**Comment by ex3ndr** [comment]
I have added popup to ask to download model if it is not exist, also you can now use provide a custom model to work with
